MvcContactos/Models/Contactos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcContactos.Models
{
    public class Contactos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }

    }
}

MvcContactos/Models/ErrorViewModel.cs
using System;

namespace MvcContactos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcContactos/Controllers/ContactosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcContactos.Models;

namespace MvcContactos.Controllers
{
    public class ContactosController : Controller
    {
        private readonly MvcContactosContext _context;

        public ContactosController(MvcContactosContext context)
        {
            _context = context;
        }

        // GET: Contactos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contactos.ToListAsync());
        }

        // GET: Contactos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactos = await _context.Contactos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactos == null)
            {
                return NotFound();
            }

            return View(contactos);
        }

        // GET: Contactos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contactos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Email,Telefono")] Contactos contactos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contactos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contactos);
        }

        // GET: Contactos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactos = await _context.Contactos.FindAsync(id);
            if (contactos == null)
            {
                return NotFound();
            }
            return View(contactos);
        }

        // POST: Contactos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Email,Telefono")] Contactos contactos)
        {
            if (id != contactos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contactos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactosExists(contactos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contactos);
        }

        // GET: Contactos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactos = await _context.Contactos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactos == null)
            {
                return NotFound();
            }

            return View(contactos);
        }

        // POST: Contactos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactos = await _context.Contactos.FindAsync(id);
            _context.Contactos.Remove(contactos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactosExists(int id)
        {
            return _context.Contactos.Any(e => e.Id == id);
        }
    }
}

MvcContactos/Views/Contactos/Create.cshtml
@model MvcContactos.Models.Contactos

@{
    ViewData["Title"] = "Agregar Contacto";
}
<br />
<br />
<h4>Ingresar Datos</h4>
     <div class="row">
         
         <div class="col-md-4">
             <div class="panel panel-primary">
                 <div class="panel-heading">Contacto</div>
                 <div class="panel-body">
                     <form asp-action="Create" id="myForm">
                         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                         <div class="form-group">
                             <label asp-for="Nombre" class="control-label"></label>
                             <input asp-for="Nombre" class="form-control" />
                             <span asp-validation-for="Nombre" class="text-danger"></span>
                         </div>
                         <div class="form-group">
                             <label asp-for="Apellido" class="control-label"></label>
                             <input asp-for="Apellido" class="form-control" />
                             <span asp-validation-for="Apellido" class="text-danger"></span>
                         </div>
                         <div class="form-group">
                             <label asp-for="Email" class="control-label"></label>
                             <input asp-for="Email" class="form-control" type="email" placeholder="correo@abc.com" size="30" required />
                             <span asp-validation-for="Email" class="text-danger"></span>
                         </div>
                         <div class="form-group">
                             <label asp-for="Telefono" class="control-label"></label>
                             <input type="tel" asp-for="Telefono" class="form-control" placeholder="809-500-5555" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" required/>
                             <span asp-validation-for="Telefono" class="text-danger"></span>
                         </div>
                         <div class="form-group">
                             <a class="btn btn-primary" onclick="guardar()"><span class="glyphicon glyphicon-ok">Guardar</a>
                             <a class="btn btn-warning" onclick="limpiar()"><span class="glyphicon glyphicon-trash">Limpiar</a>
                             <a asp-action="Index" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>Cancelar</a>
                         </div>
                     </form>
                 </div>
             </div>
         </div>
     </div>


@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

MvcContactos/Views/Contactos/Delete.cshtml
@model MvcContactos.Models.Contactos

@{
    ViewData["Title"] = "Eliminar Contacto";
}

<h2>Eliminar Contacto</h2>

<h3>Esta seguro que quiere borrar este Contacto?</h3>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading detalle">
                <h4>Contactos</h4>
            </div>
            <dl class="dl-horizontal panel-body ce">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Apellido):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Apellido)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Email):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Telefono):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Telefono)
                </dd>
            </dl>
        </div>
    </div>
    </div>
<form class="form-group" asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Borrar" class="btn btn-danger"/>
    <a class="btn btn-default" asp-action="Index"><span class="glyphicon glyphicon-arrow-left"></span> Volver Lista Contactos</a>
</form>

MvcContactos/Views/Contactos/Details.cshtml
@model MvcContactos.Models.Contactos

@{
    ViewData["Title"] = "Detalles de Contacto";
}

<h2>Detalles de Contacto</h2>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading detalle">
                <h4>Contactos</h4>
            </div>
            <dl class="dl-horizontal panel-body ce">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Apellido):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Apellido)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Email):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Telefono):
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Telefono)
                </dd>
            </dl>
        </div>
    </div>
    <div>
    </div>
</div>
<a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.Id"><span class="glyphicon glyphicon-pencil"></span> Edit</a> 
<a class="btn btn-default" asp-action="Index"><span class="glyphicon glyphicon-arrow-left"></span> Volver Lista Contactos</a>

MvcContactos/Views/Contactos/Edit.cshtml
@model MvcContactos.Models.Contactos

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Contactos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcContactos/Views/Contactos/Index.cshtml
@model IEnumerable<MvcContactos.Models.Contactos>

@{
    ViewData["Title"] = "Lista de Contactos";
}

<h2>Mi Lista de Contactos</h2>

<p>
    <a asp-action="Create" class="btn btn-success" id="add"><span class="glyphicon glyphicon-plus"></span> Nuevo Contacto</a>
</p>
<br>
<br>
<div class="row">
    <div class="col-md-10">
        <table class="table">
            <thead class="dark">
                <tr>
                    <th scope="col">
                        #
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Apellido)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) {
                <tr>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.Apellido)
                    </td>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td scope="row">
                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"><span class="glyphicon glyphicon-list-alt"></span> Detalles</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><span class="glyphicon glyphicon-trash"></span> Borrar</a>
                    </td>
                </tr>
}
            </tbody>
        </table>
    </div>
</div>

MvcContactos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contactos</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Contactos" asp-action="Index" class="navbar-brand">Contactos</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li><a asp-area="" asp-controller="Home" asp-action="Index">Mis Contactos</a></li>-->
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Contactos</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>